260-restructure-i18n-translation-json-files
Systemvetardagen/systemvetardagen.se pull request #261
Opened 2024-01-13 18:41 UTC by olehoef

I restructured the json files by page (and some times components). I also updated all the keys in the code.

2024-01-15 11:56 UTC, jazzjacob requested changes
fix the mistakes I've highlighted.

also there are inconsistencies with naming, sometimes camelCase, sometimes kebab-case, sometimes lowercase etc. but this is not urgent and we could start a new issue instead

2024-01-15 11:56 UTC, jazzjacob commented on components/Navbar.vue
> +          $t("nabbar.about")
spelling mistake

2024-01-15 11:56 UTC, jazzjacob commented on pages/catalog/index.vue
> +img<template>
"img" mistake

2024-01-22 16:02 UTC, olehoef commented
> fix the mistakes I've highlighted.
> 
> also there are inconsistencies with naming, sometimes camelCase, sometimes kebab-case, sometimes lowercase etc. but this is not urgent and we could start a new issue instead

OK thanks! The different key naming conventions still from the previous years. I would say let's do it later.

2024-01-22 16:03 UTC, merged