CompanyPage_markdown-area
Systemvetardagen/systemvetardagen.se pull request #262
Opened 2024-01-14 11:17 UTC by olehoef

I wanted to apply styles to this section without changing the global styles. However, the problem was that with v-html the html is injected into the dom before styles are calculated. Hence, a pure css solution didn't work (e.g., parent-container > h1 {...}). 

So, I had to resort to JS that waits for the DOM elements to load before it applies in-line styling. 

Long story short: I hope this works on Netlifly. Otherwise, we have to revise this again.

2024-01-15 11:45 UTC, jazzjacob commented
Does the solution in example 2 in this page not work in our case?
https://www.w3schools.com/vue/ref_v-html.php

2024-01-22 14:37 UTC, jazzjacob requested changes
See my prevous comment

2024-01-22 16:09 UTC, olehoef commented
Interesting, I will have a look at it.

2024-02-02 13:28 UTC, jazzjacob approved these changes

2024-02-02 13:34 UTC, merged